spring.application.name=06_Hiem_Sreynit_SPRING_HOMEWORK03
spring.datasource.url=jdbc:postgresql://localhost:5432/event_db
spring.datasource.username=postgres
spring.datasource.password=172772
spring.datasource.driver-class-name=org.postgresql.Driver
